- hosts: all
  gather_facts: False
  tasks:
    - name: fetch app repo for static assets
      git:
        repo=https://github.com/dolph/pasteraw.git
        dest=/var/www/pasteraw

- hosts: all
  gather_facts: False
  sudo: True
  sudo_user: pasteraw
  tasks:
    - name: fetch app repo
      git:
        repo=https://github.com/dolph/pasteraw.git
        dest=~/pasteraw

    - name: pre-install dependencies
      pip:
        name={{ item }}
        virtualenv=~/venv
      with_items:
      - distribute
      - "keyring<5.2.0"

    - name: install app
      pip:
        name=~/pasteraw
        virtualenv=~/venv
        extra_args='--editable'

- hosts: all
  gather_facts: False
  tasks:
    - name: restart supervised processes
      supervisorctl:
        name={{ item }}
        state=restarted
      with_items:
        - gunicorn
